services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=ecommerce-db
      - DB_PORT=5432
      - DB_NAME=demo-db
      - DB_USERNAME=postgres
      - DB_PASSWORD=Colombia123
      - JWT_SECRET=Colombia123
    depends_on:
      - postgres
    command: npm run start:prod
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: ecommerce-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Colombia123
      POSTGRES_DB: demo-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local

