services:
  postgres:
    image: postgres:15
    container_name: ecommerce-db
    ports:
     
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Colombia123
      POSTGRES_DB: demo-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=ecommerce-db
      - DB_PORT=5432
      - DB_NAME=demo-db
      - DB_USERNAME=postgres
      - DB_PASSWORD=Colombia123
      - JWT_SECRET=Colombia123
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local


