

services:
  nestapp:
    image: kratus66/nest-demo:latest
    ports:
      - "3001:3000"  # (Host:Container)
    env_file:
      - .env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:





